### ISSUE TITLE
Work with Raspberry Pi running Pi-hole

### ISSUE THREAD

**Issue by baronmax** [sillyfrog/currentcost-mqtt#3]
Hi!

Is there a way to make this work using a Raspberry Pi running Pi-hole?  I think I can do the re-direction in Pi hole but not sure what the next steps would be... running docker with your code?  Any assistance greatly appreciated!

**Comment by sillyfrog** [comment]
I have not see Pi-hole in action before, but if you're running it already, it would hopefully be possible to customize it for a couple of domains (as mentioned in the README), and point them to your server. If you are running this on the same server, and you already have docker running, then this running in docker would work. Note that this _must_ run on port 80, so if you have other HTTP servers on the same host, you'll need to put in a reverse proxy or move them to a different port.

Hopefully that 'll makes sense and gives you enough to get started.

Good luck!
